export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const RESET_TO_DEFAULT = 'RESET_TO_DEFAULT';